### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by toucham**
**Changes:**
- update api packages (since there were conflicts and was unable to run `pip install -r requirements.txt`
- add .gitignore for python venv

### CODE REVIEW

**Review by IanSaucy — APPROVED** [review]
lgtm

**Comment by IanSaucy** [comment]
Do you want me to merge this? @toucham

**Comment by toucham** [comment]
I'm still unable to merge. It requires more reviews to merge it 😅

**Comment by IanSaucy** [comment]
Oops, just fixed that!

**Pull request merged**
